packages:
  - "packages/*"
  - "apps/*"
  - "services/*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@swc/core": true
  bcrypt: true
  electron: true
  esbuild: true
  prisma: true
  unrs-resolver: true

onlyBuiltDependencies:
  - electron
  - esbuild
  - "@prisma/engines"
  - "@prisma/client"
  - bcrypt
  - prisma
  - unrs-resolver
